# ansible-playbook -i inventory.ini rpi-homeassistant.yml
# semaphore / cli argument example for vars_prompt
#   ex: ["-e","hostname='your_hostname' wifi_ssid='your_ssid' wifi_password='your_password'"] 
---
- hosts: homeassistant
  remote_user: pi
  become: true
  vars:
      wifi_country: "US"
      locale: "en_US.UTF-8"
      keyboard_layout: "us"
      timezone: US/Eastern
      haconfigdir: "/home/homeassistant/haconfig"

  vars_prompt:
    - name: hostname
      prompt: "please enter a hostname for your new device:"
      private: no
#    - name: wifi_ssid
#      prompt: "please enter the WiFi SSID for your new device:"
#      private: no
#    - name: wifi_password
#      prompt: "please enter the WiFi password for your new device:"
#      private: yes

  tasks:
    - name: Upgrade all packages to the latest version
      apt:
        name: "*"
        state: latest

    - name: install base packages
      apt:
        state: latest
        pkg:
          - vim

    - name: docker environment
      apt:
        state: latest
        pkg:
          - docker.io

    # FIXME: setup wpa_supplicant.conf (maybe?)

    # set time zone
    - name: update tzdata
      become: true
      file:
        src: /usr/share/zoneinfo/{{ timezone }}
        dest: /etc/localtime
        owner: root
        group: root
        state: link

    # set the hostname
    - name: Set the hostname
      become: yes
      file:
          path: /etc/hostname
          mode: 644
          group: root
          owner: root
          content: |
            {{ hostname }}

    # Set the hostname in /etc/hosts too
    - name: Set the other hostname
      become: yes
      replace:
        path: /etc/hosts
        regexp: '(\s+)raspberrypi$'
        replace: '\1{{ hostname }}'

    # FIXME: run rpi-update

    # enable sshd
    - name: ensure sshd is enabled
      systemd:
        name: ssh
        state: started
        enabled: yes

    # copy ssh key to pi user
    - name: copy my ssh key to pi user
      authorized_key:
        user: pi
        state: present
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

    # change pi user password
    # https://stackoverflow.com/questions/33972756/ansible-to-generate-random-passwords-automatically-for-users
    - name: set a new password for the default "pi" account
      become: yes
      user:
        name: "{{ item }}"
        password: "{{ lookup('password', 'credentials/' + item + '/password.txt encrypt=md5_crypt') }}"
      with_items: ['pi']

    # setup homeassistant config directory
    - name: setup homeassistant user for config
      user:
        name: "homeassistant"
    
    - name: setup homeassistant config dir
      file:
        path: "{{ haconfigdir }}"
        state: directory
        mode: 0644
        owner: homeassistant
    
    - name: get homeassistant user info
      getent:
        database: passwd
        key: "homeassistant"

#    - debug:
#        var: getent_passwd

    # setup homeassistant systemd unit
    - name: create homeassistant docker config
      become: yes
      copy:
          dest: /etc/systemd/system/docker@homeassistant.service
          mode: 0644
          owner: root
          group: root
          content: |
            [Unit]
            Description=Home Assistant Container
            After=docker.service
            Requires=docker.service

            # https://blog.container-solutions.com/running-docker-containers-with-systemd
            [Service]
            TimeoutStartSec=0
            Restart=always
            ExecStartPre=--/usr/bin/docker stop %i
            ExecStartPre=--/usr/bin/docker rm %i
            ExecStartPre=/usr/bin/docker pull homeassistant/raspberrypi3-homeassistant:stable
            ExecStart=/usr/bin/docker run --rm --name %i \
              -v {{ haconfigdir }}:/config \
              -v /etc/localtime:/etc/localtime:ro \
              -e PUID={{ getent_passwd["homeassistant"][1] }} \
              -e PGID={{ getent_passwd["homeassistant"][2] }} \
              --net=host \
              --device /dev/ttyACM0 \
              homeassistant/raspberrypi3-homeassistant:stable

            [Install]
            WantedBy=multi-user.target

    - name: start docker homeassistant
      systemd: state=started name=docker@homeassistant daemon_reload=yes

