---
# setup homeassistant config directory
- name: setup homeassistant user for config
  user:
    name: "homeassistant"

- name: setup homeassistant config dir
  file:
    path: "{{ haconfigdir }}"
    state: directory
    mode: 0644
    owner: homeassistant

- name: get homeassistant user info
  getent:
    database: passwd
    key: "homeassistant"

# setup homeassistant systemd unit
- name: create homeassistant docker config
  become: yes
  template:
    src: docker@homeassistant.service.j2
    dest: /etc/systemd/system/docker@homeassistant.service
    mode: 0644
    owner: root
    group: root

- name: start docker homeassistant
  systemd: state=started name=docker@homeassistant daemon_reload=yes

